all:
	pio -f -c vim run

upload:
	pio -f -c vim run --target upload

clean:
	pio -f -c vim run --target clean

commands:
	pio -f -c vim run --target compiledb

program:
	pio -f -c vim run --target program
	

uploadfs:
	pio -f -c vim run --target uploadfs

monitor:
	pio device monitor -b 115200

update:
	pio -f -c vim update

